### ISSUE TITLE
[Attributed Strings] Create default `Styler` for attributed string rendering

### ISSUE THREAD

**Issue by iwasrobbed** [iwasrobbed/Down#138]
We introduced a new AST renderer in https://github.com/iwasrobbed/Down/pull/132

Next, we should create a default `Styler` which people can easily override so they can get up and running with attributed string rendering

**Comment by ksparakis** [comment]
What's the status of this? 
:)

**Comment by iwasrobbed** [comment]
@ksparakis As with all open source work that is provided by volunteers in their free time, the status is "Waiting for someone from the community to lend a helping hand".

There's nothing preventing you from styling the attributed string yourself by conforming some class to `Styler`. This issue is open to provide the community with a default `Styler` implementation that can be easily adjusted, rather than each person implementing their own.

**Comment by johnxnguyen** [comment]
I am willing to implement this styler and have been thinking a bit about it since finishing https://github.com/iwasrobbed/Down/pull/132. I will finally have some free time this weekend so I'll see how far I get.

**Comment by rob-keepsafe** [comment]
Thanks for the help, @johnxnguyen ! I'm on paternity leave for a bit, but will be around when I can

**Comment by iwasrobbed** [comment]
Thanks for the help, @johnxnguyen ! I'm on paternity leave for a bit, but will be around when I can

**Comment by johnxnguyen** [comment]
Congratulations @iwasrobbed !

**Comment by irskep** [comment]
I started working on one of these without realizing the project needed a contribution and just ran across this issue, so I'm very happy to show you what I have so far with a public domain license: https://gist.github.com/irskep/ab050304371e5730feee7fffea57b389

I'm hitting a snag with list handling, though: it looks like I don't have enough information to figure out what level of nesting the list items are, and I'm also having trouble applying paragraph styles to the list correctly (setting paragraphSpacing only on the last item).

**Comment by irskep** [comment]
Chased it down some more. Lists in NSAttributedString seem extremely tricky and will probably need much more sophisticated handling than the visitor is doing right now.

See the comment on this article from last year https://www.meandmark.com/blog/2016/12/adding-markers-to-text-lists-when-pressing-the-return-key/

**Comment by johnxnguyen** [comment]
@irskep indeed I've also found from previous experience that formatting the lists are by far the hardest part. As you've alluded to, we need to be able to handle an arbitrary nesting depth, but care should also be taken so that the paragraph styles are applied correctly and that there are not overlapping and conflicting paragraph styles.

In regards to determining the nesting depth, I think it would be easier and cleaner to use the AST. Although there isn't yet a `parent` property on the `BaseNode`, we could easily expose one. Then we would simply find the nesting depth of a particular `List` node by following the path up to the root `Document` node, counting along the way how many other `List` nodes we pass.

**Comment by NicolasLourenco** [comment]
I'm facing the same issue for formatting the lists with different level of imbrication. @johnxnguyen did you have more informations since the last week about that?

**Comment by johnxnguyen** [comment]
@NicolasLourenco I spent the weekend trying to tackle this problem and I believe I've made some good progress. 

Firstly, there are a few things we need to consider when formatting nested lists with `NSParagraphStyle`:

1. Paragraph styles should be applied over paragraphs, (obvious I know, but you get all sorts of unexpected issues when your paragraphs are only partially applied).
2. There should be only one paragraph style applied over a range of characters. There is a `fixAttributes(in: NSRange)` which will tidy up your paragraph styles, but in our case we need to more control.
3. Nested lists and items are styled before outer lists and items.
4. When we implement the `style(item str: NSMutableAttributedString)` protocol method, we have to keep in mind that the current item we are styling (contained in `str`), may contain a nested list.

As a result, adding a paragraph style to a list item leads to a lot of headaches, because we have to make sure that we don't overwrite existing paragraph styles formatting any the nested lists.

I'm taking the approach where we selectively apply paragraph styles to individual paragraphs within a list item, depending on their order and the presence of nested lists. Long story short, when styling a list item, we only add paragraph styles to the paragraphs that don't already have a paragraph style.

There is of course a lot more to it... such as determining which part of the list item (`str`) contains a nested list, among other things.

One thing I learned yesterday is that a list item can contain a nested list anywhere among its content. That is, you shouldn't assume it will be at the end of the list item. **I highly recommend creating all sorts of nested list structures and inspecting the AST in the debugger.** You can use the `DebugVisitor` for this purpose.

**Comment by johnxnguyen** [comment]
I've pushed my local branch to `feature/default-styler` for anyone interested. It's a work in progress of course, but the list formatting is working nicely.

**Comment by NicolasLourenco** [comment]
Thank you @johnxnguyen, I will take a look

**Comment by ykphuah** [comment]
I gave it a spin, it looks really good! However, I wanted to make the overall fonts smaller, and I realize that I can't override the FontBook. I tried to just move the whole DefaultStyler and FontBook class into my project, but then it is using some extensions that is not public.

Do you mean for the DefaultStyler to be copy pasted? or subclassed? or configured (e.g. passing in a Fontbook when constructing) ?

**Comment by johnxnguyen** [comment]
@ykphuah yeah I have been focusing on the list formatting and there's a lot of changes still to be made. 

The idea with the font book is to allow the Styler to accept various font generating sources, so you could create a font book with explicit fonts and sizes, or you can use a font book that uses dynamic type, or any other way you might get your fonts.

I will make the default Styler open to subclassing, but my intention is to make the default Styler work for 80% of the use cases so you would only need to subclass it if you really need to.

The default Styler will have a lot more configurations for colors and spacings, but I haven't gotten that far yet.

If you want to play around more with the implementation, you can drag the whole Down project into your xcode project and then manipulate it however you want.

Your feedback is always welcome, whether you'd like to see a particular feature or find a particular bug.

**Comment by ykphuah** [comment]
@johnxnguyen  thanks for the good work. I have grown to like the smaller overall size text and also no spacing between paragraph/lists of MarkdownKit, so these are the two that I would need to "customize" before migrating to this.

**Comment by Orion98MC** [comment]
Hi there,

I'm working on an iOS app, written in Swift, that needs a "Help System" much like in macOS Apps where the user can browse different subjects etc... The solution I came with is a Wiki kind of help system. And quite naturally I wanted to use a Markdown library to help the designing of the contents (pages). I also added a macOS target that allows viewing and in place editing of the Wiki contents. Due to this I wanted to keep it simple and have the wiki content rendered in a (UI|NS)TextView thus rendering markdown as NSAttributedString. 

The default ```Down(markdownString: string).toAttributedString()``` works great but now I am willing to integrate inline images in the page rendering. However, since I want the images to be local (not online) I need to be able to control the image loading and I have noticed that the ```Styler``` protocol could be what I'm looking for. But the master branch of ```Down``` does not seem to include any default Styler and I was wondering if you have one ready for subclassing or not in the pipe that I could 'beta-test'. Alternatively if you have any idea how I could solve this inline local image rendering I'm open to suggestions.

Thanks and best regards,
Thierry

**Comment by johnxnguyen** [comment]
Hi @Orion98MC , the default styler is still a work in progress, but it is in a working state so you are welcome to check out `feature/default-styler` and play around with image loading. I plan to finish the styler within the next four weeks.

Personally I haven't used `Down` to display images, but it shouldn't be too hard. Thinking about it now, the `AttributedStringVisitor` may need modification. This is where you would need to parse the image path, fetch the image, and add it as an `NSTextAttachment`. The styling method for the image could perhaps be used to change the position the size of the image.

In any case, have a play and let me know how you go. I would like to add proper support for images, so if you have any ideas about what kind of functionality you expect out of the box, let me know.

**Comment by spicymatt** [comment]
Hello. Is the support for dark mode a task for the Styler ?
Thanks and regards
matthieu

**Comment by johnxnguyen** [comment]
@spicymatt yes. The idea is to have a protocol that encapsulates specifying colors to be used by the styler. A concrete implementation of the protocol could then consider light and dark modes.

**Comment by mglass** [comment]
@johnxnguyen I put what I'm using for image support into a PR for you. Fairly basic, and iOS only, but it handles animated gifs as well. #163

**Comment by iwasrobbed** [comment]
Hi all 👋 Just a reminder: Let's please keep this issue's conversation focused around implementing a styler default. Anything else, please file a separate issue or just an open a PR and tag one of us to review. Thanks!

**Comment by tsfischer** [comment]
Is there any active work still being done on the default styler since the above comments? 

This library, using the standard toAttributedString() method, gets us very close to what we need, but I need to be able to override default text colors, font sizes, etc. The stylesheet isn't workable as it doesn't support switching between light and dark mode, and indeed currently doesn't appear to support dark mode at all.

I haven't yet checked out the feature branch, but it sounds like image processing isn't implemented yet? That's also crucial for us (and currently working with the html-based parsing).

We are currently using a library called TSMarkdownParser but that one doesn't seem to be supported anymore and has some flaws.

Thanks!

**Comment by johnxnguyen** [comment]
Hi @tsfischer , I've gotten the implementation to an almost finished state, after working on it quite regularly in the last month or so. I wanted to open a PR in the last weeks but have been on holiday (just got back today) and couldn't find the time unfortunately. I need to add some documentation  and do a final look through to clean up loose threads, but I reckon I can get that done in the next few days. There's quite a lot to review so I'm not sure how long it will be until it's merged.

One thing to note is that I haven't added support for image loading yet. I think it needs some thought about how to implement it in a way that is flexible for loading image data from different sources (local or remote). If you have some suggestions or ideas I'd be interested to hear. I was thinking along the lines of a protocol `ImageProvider` (or something like that) that defines two methods, one for a placeholder and one for the content for a given uri. Image support is next on my todo list for Down 😄

**Comment by tsfischer** [comment]
Thanks for the reply. We're currently using TSMarkdown but are having some issues and it doesn't appear to be very supported anymore. Down looked promising, but the HTML-to-NSAttributed workflow is slow and things need to be specified by CSS which causes problems with things like dynamic colors and switching between light/dark mode (as well as being clunky for a native app dev like myself to work with).

So... a Styler implementation would be great... but we need image support. I'm also considering the CocoaMarkdown library but that one has its own cumbersome bits, such as the refusal to support Cocoapods.

Thanks for your work with this project.

**Comment by johnxnguyen** [comment]
I've opened a draft PR https://github.com/iwasrobbed/Down/pull/177 for anyone interested.

**Comment by twi123** [comment]
Guys, is there any thoughts about migrate whole thing to `cmark-gfm` (for supporting of strikethrough and tables)? 

@tsfischer image support is possible via something like AsyncTextAttachment... But tables... Without core (cmark) changes i think its just impossible (

**Comment by iwasrobbed** [comment]
Hi @twi123 👋 Please keep the conversation focused on the `Styler` protocol within Down.

- cmark-gfm is Github-flavored markdown, not the CommonMark standard. You're welcome to use the fork here: https://github.com/mknabe/Down-gfm
- I believe you mean `NSTextAttachment`

**Comment by twi123** [comment]
@iwasrobbed thanks for link to `Down-gfm` fork!
No, i mean extension of `NSTextAttachment` like this [AsyncTextAttachment](https://github.com/Cocoanetics/Swift-Examples/blob/master/Attachments/Attachments/AsyncTextAttachment.swift)
