### ISSUE TITLE
Pass DownOptions to DownView

### ISSUE THREAD

**Issue by ladislas** [iwasrobbed/Down#147]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I was using Down v0.5.2 that was working great for my use case: a markdown file with a lot of inline html `<span class="myClass"></span>` that I used to render specific words or lines with my custom CSS.

Then I upgraded to v0.8.2...

## What did you expect to happen?

Nothing, just to keep working the way it was.

## What happened instead?

Rendering and custom css works for generic elements but my `spans` are gone and/or are not rendered anymore. Even simple `<strong></strong>` are removed :( 

## Analysis & Next step

The reason is that in `DownView`, we render HTML with the `.default` `DownOptions`.

Would you accept a PR that adds the ability to specify an option when calling `update(:)`? Or setting a `var` that would be read by `loadHTMLView(:)`?

If so, I can make one now :) That would make my life easier with my current codebase...

Best,  
-- Ladislas

**Comment by iwasrobbed** [comment]
Hi @ladislas 👋 Correct, the HTML sanitization behavior changed so that it sanitizes HTML by default, so I'd be open to adding a `DownOptions` argument to both the `init` and `update` methods on `DownView`

I'm more than happy to accept a PR for these (thank you for offering), just please be sure to add a quick test in `DownViewTests` so we make sure we don't break this in the future 👍

**Comment by ladislas** [comment]
Great! Thanks for the quick reply, will do asap! :)

**Comment by iwasrobbed** [comment]
@ladislas 🚀 Released as v0.8.3, thanks again for raising an issue

**Comment by ladislas** [comment]
Thanks a lot for merging the changes quickly :)
