### ISSUE TITLE
Text Size of DownView too small

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [iwasrobbed/Down#15]
I added Down to my current project to display markdown on different views in different layouts. 
For me it seems the text ist a little bit too small to be good readable. 
I made some changes to the css file to display a bigger font size. 

I am not sure if there is another way, like a config file, but that worked for me and could be an addition to the project. 
https://github.com/Sn0wfreezeDev/Down/commit/c0d3f51c80f5782497f680e7a4dd2b4fceea6888

**Comment by iwasrobbed** [comment]
@Sn0wfreezeDev Instead of modifying the minified css file directly, you should likely just add your own css file that gets included and then you can use that to override the default css implementation.

As much as possible, I'd rather Down act as a generic renderer and allow others to set styling how they'd like.
