### ISSUE TITLE
Down cannot convert this markdown string to html

### ISSUE THREAD

**Issue by zhifeng-huang** [iwasrobbed/Down#190]
This is the string:

`Test**. &nbsp;This is bold**. This is normal_&nbsp; Italics_. Normal again.`

When I try to convert it to HTML by using Down, it gives me this:

`<p>Test**.  This is bold**. This is normal_  Italics_. Normal again.</p>`

It cannot recognize ** and _ .

**Comment by iwasrobbed** [comment]
That's probably because it's not valid Common Markdown. Please [read the documentation](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis) and try it for yourself https://spec.commonmark.org/dingus

If you feel there's a mistake, you're welcome to open a ticket in the upstream [cmark repo](https://github.com/commonmark/cmark)
