### ISSUE TITLE
hard blank line insertion after list

### ISSUE THREAD

**Issue by slashlos** [iwasrobbed/Down#210]
Tried various encodings to feature a separating blank line after a bullet list, so the next paragraph is not immediately after the list; tried all sorts of remedies here:
[
Create two blank lines in Markdown - Stack Overflowstackoverflow.com › questions › create-two-blank-lines...](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwihrZaL-azpAhXooHIEHUAeAWEQFjABegQIChAE&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F20543454%2Fcreate-two-blank-lines-in-markdown&usg=AOvVaw1Z-KPcvdYYaI6eyAYRbVTE)

but no joy.

/los

**Comment by rob-keepsafe** [comment]
Hi @slashlos 👋 [Please file in `cmark`'s repo](https://github.com/commonmark/cmark) which is the Markdown engine running within Down and feel free to let us know once/if it's resolved. All of this is based upon the CommonMark standard so if it's part of the standard, then it should work; else, you can ask for it to be part of the standard.

**Comment by slashlos** [comment]
That’s a “bug” database as it was summarily closed, and I get that, but the pkg is not performing as native md; it’s why I filed here. If there’s a recipe or how to, throat would be great. There is no where else to go aside from adopting an alternative. Too bad

**Comment by iwasrobbed** [comment]
As was stated, Down is just Swift bindings for the underlying `cmark` library (one of many bindings in many languages) and is based on the CommonMark standard. If there's a bug in the bindings, feel free to file one. Otherwise, please direct bugs to the underlying lib (cmark).

And as with any open source code, it's not just the maintainer's responsibility to fix everything at someone else's direction or to be someone else's personal StackOverflow. You're free to use whichever lib you choose
