### ISSUE TITLE
[Legacy API] toAttributedString() adding trailing newline via `toHTML()`

### ISSUE THREAD

**Issue by gsbernstein** [iwasrobbed/Down#219]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

Example code:
``` swift
            let down = Down(markdownString: "test")            
            let attributedString = try! down.toAttributedString()
```

## What did you expect to happen?

attributedString.string == "test"

## What happened instead?

attributedString.string == "test\n"

Seems like internally `toAttributedString()` uses `toHTML()`, and `toHTML()` is the one adding the newline.

**Comment by gsbernstein** [comment]
It seems like your NSAttributedStringTests even expect the trailing newline to be added. Is this intended behavior?

```
    func testAttributedStringBindingsWork() {
        let attributedString = try? Down(markdownString: "## [Down](https://github.com/iwasrobbed/Down)").toAttributedString()
        XCTAssertNotNil(attributedString)
        XCTAssertTrue(attributedString!.string == "Down\n")
    }

    func testInstantiation() {
        let attributedString = try? NSAttributedString(htmlString: "<html><body><p>Oh Hai</p></body></html>")
        XCTAssertNotNil(attributedString)
        XCTAssertTrue(attributedString!.string == "Oh Hai\n")
    }
```

**Comment by rob-keepsafe** [comment]
Hi @gsbernstein 👋 I would likely switch to using the attributed string styler API (which is background thread safe as well) rather than that legacy API which does indeed use `toHTML()` under the hood. We have no control over how they render their string w/ that API but with the attributed string styler you can do whatever you wish

See https://github.com/iwasrobbed/Down/pull/177

and examples in the test suite, e.g. https://github.com/iwasrobbed/Down/blob/master/Tests/Styler/StylerTestSuite.swift#L64

**Comment by gsbernstein** [comment]
Thanks Rob! Does that API support using a stylesheet? Our current full code looks like this
```
let style = "* {font-family: \(cssFont.family.cssString); color: \(cssColor); font-size: \(cssFont.size.rawValue)px; } a { color: \(cssLinkColor); text-decoration: none; } *:last-child { margin-bottom:0; padding-bottom: 0;}"
let attributedString = try down.toAttributedString(stylesheet: style)
```
And I'm not sure if DownStylerConfiguration lets you do all of that (or how to translate it)

**Comment by johnxnguyen** [comment]
@gsbernstein unfortunately no it currently does not support using a stylesheet.

**Comment by rob-keepsafe** [comment]
No style sheets, but you could set general styles like John does here https://github.com/iwasrobbed/Down/blob/master/Tests/Styler/StylerTestSuite.swift#L90

If you need more custom styling, you could also fork the repo and add it in (such as your `last-child` styling) but there are already some APIs for spacing between list items

**Comment by iwasrobbed-ks** [comment]
@o15a3d4l11s2 I'm curious why you wouldn't just use an attributed string transform for sub/superscript instead of opting into HTML? E.g. https://github.com/Flinesoft/HandyUIKit/blob/3353856a1d50df5ffd370ded078c1a21ffb18a68/Frameworks/HandyUIKit/Extensions/NSAttributedStringExt.swift#L55

Otherwise, no, handling any sort of HTML requires switching into unsafe mode since HTML code isn't safe for raw rendering without opening up your app to various scripting attacks

**Comment by o15a3d4l11s2** [comment]
@iwasrobbed-ks, thanks for the fast response and the suggested alternative. I have external constraints, so I need to support <sup> and <sub> explicitly. I resolved the end newline issue and all works properly now. Thank you for creating this library!
