### ISSUE TITLE
Can I get just the ranges of Markdown objects?

### ISSUE THREAD

**Issue by WillBishop** [iwasrobbed/Down#235]
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I tried to get just the ranges of the recognised markdown strings. I used `enumerateAttributes` on an `NSAttributedString`, which _worked*_ but it gave the ranges _after_ parsing (as I'd expect). So in the string 

> This is a **bold** word

The range of bold text is `9..<13`, as parsing strips out the `**`. But I wish to create a writing app which keeps the markdown visible, so I'm wondering if there's a way I don't know about to get the range of the world 'bold' in this instance, along with accompanying information to signify that I should make it bold on my own..

## What did you expect to happen?

It did what I expected, but I'm wondering if there's something I'm missing.

**Comment by johnxnguyen** [comment]
Hi @WillBishop , in general, if you have questions about the structure of your text then you would want to be working with the abstract syntax tree generated from the parsing stage. You would achieve this by implementing your own `Visitor` object (see `AttributedStringVisitor` for ideas).

However, I must warn you that if your goal is to have a markdown editor with live rendering (i.e styling as you type, like in [Bear](https://bear.app)), then you will run difficulties quite quickly. The problem is that you would need to have a 1:1 character correspondence between the input string and the rendered output string, which isn't something that cmark has and is difficult / impossible to support without modifications to the cmark code. I'm happy to elaborate it further if you'd like to know more.

**Comment by iwasrobbed-ks** [comment]
Closing this for now due to no response and unlikely to support it in cmark
