### ISSUE TITLE
Markdown tables support

### ISSUE THREAD

**Issue by raajvijay** [iwasrobbed/Down#36]
This is more of a question than an issue.
Does this library support markdown tables conversion to HTML? It doesn't work as far I checked.

**Comment by iwasrobbed** [comment]
@raajvijay CommonMark never originally supported tables as a core feature since it wasn't part of the markdown spec (people did them as one-off extensions).

GitHub is now using cmark (the library acting as the engine for this repo) and has added an extensions API that does do tables. It wouldn't be a lot of work to fork this repo and compile it w/ that lib instead, but I'd rather not do this since it's GitHub-flavored markdown versus CommonMark.

See: https://github.com/jgm/cmark/compare/master...github:master

**Comment by raajvijay** [comment]
Thanks for the quick reply.

**Comment by venkatkonda** [comment]
Is table format supporting now?

**Comment by venkatkonda** [comment]
@iwasrobbed Is table format supporting now?

**Comment by Tiaotiaotiao** [comment]
> @raajvijay CommonMark never originally supported tables as a core feature since it wasn't part of the markdown spec (people did them as one-off extensions).
> 
> GitHub is now using cmark (the library acting as the engine for this repo) and has added an extensions API that does do tables. It wouldn't be a lot of work to fork this repo and compile it w/ that lib instead, but I'd rather not do this since it's GitHub-flavored markdown versus CommonMark.
> 
> See: [commonmark/cmark@master...github:master](https://github.com/commonmark/cmark/compare/master...github:master)

NO

**Comment by Tiaotiaotiao** [comment]
> @iwasrobbed Is table format supporting now?

NO
