### ISSUE TITLE
Can not load local image and link to local .md file

### ISSUE THREAD

**Issue by Cu-Toof** [iwasrobbed/Down#40]
I want to load local image and link to local .md file in .md file. So, I want to know subclasses that I have to edit. Could you please tell me?, thank you

**Comment by ladislas** [comment]
@Cu-Toof here is my solution.

Just drop a text file containing your content anywhere in your project and use the following in your code:

``` swift
import UIKit
import Down

class ViewController: UIViewController {

    var downView: DownView?

    override func viewDidLoad() {

        super.viewDidLoad()


        let path = Bundle.main.path(forResource: "NameOfMyFile", ofType: "txt")
        let content = try? String(contentsOfFile: path!, encoding: String.Encoding.utf8)

        print(content!)

        downView = try? DownView(frame: self.view.bounds, markdownString: "\(content!)") {
            self.view.addSubview(self.downView!)
        }

    }

}
```

**Comment by Cu-Toof** [comment]
I want to click a link in the content of WKWebView to show a .md file that is saved in local and my solution is WKScriptMessageHandler. But I have an issue, I can't set WKWebViewConfiguration because DownView class has inited WKWebView with WKWebViewConfiguration default. So, I have not used DowView and custom a new WKWebView. Could you please edit DownView class with init method that can set WKWebViewConfiguration. WKWebViewConfiguration will help developer can handle javascript in WKWebView.

**Comment by ladislas** [comment]
and as for the images not loading, the problem comes from the [`baseURL`](https://github.com/iwasrobbed/Down/blob/806fc0b78af9bbff132a18be28d2631bf7e686d0/Source/Views/DownView.swift#L73) used when [`loadHTMLString`](https://github.com/iwasrobbed/Down/blob/806fc0b78af9bbff132a18be28d2631bf7e686d0/Source/Views/DownView.swift#L87) is called, it resolves to the `DownView.bundle` url inside the pod and therefore cannot find pictures that are in your own project.

The solution I found was to:

- copy the content of the [`DownView.bundle`](https://github.com/iwasrobbed/Down/tree/master/Resources/DownView.bundle)  
![screenshot 2017-08-18 10 19 30](https://user-images.githubusercontent.com/2206544/29450403-dbdda468-83fe-11e7-9388-188f09cbc9e3.png)
- and put it inside my own `resources` **group** in my project and add them as `groups` and **NOT** as `folder references`
![screenshot 2017-08-18 10 21 40](https://user-images.githubusercontent.com/2206544/29450450-0b67f256-83ff-11e7-8ea1-823c45ebe429.png)
- now you just need to instantiate `DownView` with your own `templateBundle`, now being `Bundle.main` like this:

```swift
downView = try? DownView(frame: self.view.bounds, markdownString: content, templateBundle: Bundle.main) {
    self.view.addSubview(self.downView!)
}
```

or in the whole `ViewController.swift`:
 
```swift
import UIKit
import Down

class ViewController: UIViewController {

    var downView: DownView?

    override func viewDidLoad() {

        super.viewDidLoad()

        let path = Bundle.main.path(forResource: "content", ofType: "md")
        let content = try! String(contentsOfFile: path!, encoding: String.Encoding.utf8)

        downView = try? DownView(frame: self.view.bounds, markdownString: content, templateBundle: Bundle.main) {
            self.view.addSubview(self.downView!)
        }

    }

}
```

- finally, you have to edit the content of `index.html` to resolve to the right files by removing `css/` and `js/` where needed:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=640"/>
    <link charset="utf-8" href="down.min.css" rel="stylesheet">
    <script charset="utf-8" src="highlight.min.js" type="text/javascript"></script>
    <script charset="utf-8" src="down.js" type="text/javascript"></script>
    <title></title>
</head>
<body>
    DOWN_HTML
</body>
</html>
```

You can now add your own images in the `img` group and reference them in your markdown as `![](imageName.jpg)` **without** the group prefix, e.g. `![](doggy.jpg)`

You can also add your own css and js as long as you reference them in `index.html`.

**Comment by ladislas** [comment]
@Cu-Toof said:

> Could you please edit DownView class with init method that can set WKWebViewConfiguration. WKWebViewConfiguration will help developer can handle javascript in WKWebView.

Try my solution and if it doesn't work, why not make a pull request yourself to add this feature?

**Comment by iwasrobbed** [comment]
Thanks for your help @ladislas 💯 I'm happy to review any pull requests to improve upon this

**Comment by iwasrobbed** [comment]
Closing this for now; feel free to re-open for any PRs or further help needed
