### ISSUE TITLE
NSAttributedString to Raw string

### ISSUE THREAD

**Issue by LinusGeffarth** [iwasrobbed/Down#82]
Is it possible to create a raw string from an `NSAttributedString`?  
I'm thinking of something like `Down(attributedString: "bold, italic, regular").rawString` –> `"**bold**, *italic*, regular"`.

Reason:  
I want my users to be able to style a text (using the regular `BIU`) and then convert it to a raw string which I can store in the database to later convert that string back to a rendered `NSAttributedString`.

Thanks!

**Comment by iwasrobbed** [comment]
Down is not meant to parse attributed strings and backward convert them into Markdown. It's only a one-way transformer from Markdown into other formats.

I would recommend looking at [BonMot](https://github.com/Raizlabs/BonMot) since it can probably help you do edit-in-place styling and then saving to and restoring from plaintext (i.e. have a look at `bonMotDebugString`).

**Comment by LinusGeffarth** [comment]
I feel like this feature blends seamlessly into the functionalities of this awesome library. Too bad.
Thanks anyway!
