### ISSUE TITLE
[cmark] Some characters are escaped twice

### ISSUE THREAD

**Issue by krummler** [iwasrobbed/Down#99]
First off, thanks for this great library!

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?
Entered multiple html-excaped characters into the content of a `DownView`

## What did you expect to happen?

I expect characters to be rendered like their unescaped counterparts, for example:
- `&amp;` becomes `&`
- `&quot;` becomes `"`
- `&lt;` becomes `<`

## What happened instead?

Most characters seem to work fine, except for `&gt;` and `&lt;` (maybe there are more cases). 
- `&amp;` stays `&amp;` which renders as `&`
- `&quot;` stays `&quot;` which renders as `"`
- `&lt;` becomes `&amp;lt;` which renders as `&lt;`
- `&gt;` becomes `&amp;gt;` which renders as `&gt;`

**Comment by iwasrobbed** [comment]
Thanks for filing this @krummler; this is an issue in the underlying `cmark` lib. We are using the stable version 0.28.3 so you'd need to file a feature request in the [cmark](https://github.com/commonmark/cmark/issues/new) repo.

Confirmed

```
&amp; Hello\n\n&quot; Hai\n\n&lt; Does that work\n\n&gt; Maybe
```

becomes

```
"<p>&amp; Hello</p>\n<p>&quot; Hai</p>\n<p>&amp;lt; Does that work</p>\n<p>&amp;gt; Maybe</p>\n"
```

**Comment by krummler** [comment]
Hi Rob, 

I make an issue: https://github.com/commonmark/cmark/issues/276. I'll report back if there are any significant changes.

**Comment by phoney** [comment]
They deny they can reproduce this on the cmark project in that issue#276. The date that 0.28.3 PR was merged into Down is the same day as @iwasrobbed 's comments above (it says 18 days ago). When I attempt to reproduce this with Down 0.6.1 it seems to work correctly. I get 

`<p>&amp; Hello</p>\n<p>&quot; Hai</p>\n<p>&lt; Does that work</p>\n<p>&gt; Maybe</p>`

which I think is correct. Is it possible this was fixed in the cmark update?

![screen shot 2018-11-28 at 4 14 27 pm](https://user-images.githubusercontent.com/3106038/49182617-c12d1a00-f328-11e8-872e-70371a7af22d.png)

**Comment by iwasrobbed** [comment]
Thanks for checking @phoney! Please verify with the latest Down release and re-open this issue if it continues. It might just be an encoding issue if so @krummler

**Comment by krummler** [comment]
Hi there, thanks for the feedback, it seems to work fine now!
